export const en = {
  title: 'PingComp', subtitle: 'Lead ops workspace', brief: 'Brief', refresh: 'Refresh', agent: 'Agent', dashboard: 'Dashboard', leads: 'Leads', interviews: 'Interviews', enrich: 'Enrich Queue', outreach: 'Outreach Center', emails: 'Emails', leadId: 'Lead ID', email: 'Email', from: 'From', to: 'To', sentAt: 'Sent At', subject: 'Subject', sender: 'Sender', content: 'Content',
  filter: 'Filter', reset: 'Reset', search: 'Search name/owner/vertical/source/tags', minScore: 'Min score', status: 'Status', region: 'Country/Region', creator: 'Creator', pageSize: 'Page size',
  page: 'Page', lockOnly: 'Locked only', prev: 'Prev', next: 'Next', edit: 'Edit', saveLock: 'Save & lock', total: 'Total leads',
  locked: 'Manual locked', avg: 'Avg score', lockRate: 'Lock ratio', exportCsv: 'Export CSV', runBatch: 'Run batch (20)',
  enqueue: 'Enqueue', noData: 'No data', loading: 'Loading…', trend7d: '7-day update trend', scoreDist: 'Score distribution', enrichDist: 'Enrich status',
  enrichConceptAlert: 'This section is still a concept design and is not finished yet.',
  bulkAction: 'Bulk action', apply: 'Apply', selected: 'Selected', quickViews: 'Quick views', savedViews: 'Saved views', saveView: 'Save current view', deleteView: 'Delete view', viewName: 'View name', account: 'Account', logout: 'Logout', delete: 'Delete', deleteConfirm: 'Delete this lead?', deleteModalTitle: 'Confirm deletion', deleteModalDesc: 'This operation cannot be undone.', cancel: 'Cancel', confirmDelete: 'Delete', askAgent: 'Ask Agent', askPlaceholder: 'e.g. find leads with score >= 80 and a specific owner', sessions: 'Sessions', newSession: 'New Session', deleteSession: 'Delete Session', sessionName: 'Session Name', addLead: 'Add Lead', addLeadTitle: 'Create Lead', createLead: 'Create Lead', createLeadSuccess: 'Lead created', createLeadFailed: 'Failed to create lead', saveLeadFailed: 'Failed to save lead', networkError: 'Network error. Please try again.', nameVerticalRequired: 'Name and Vertical are required',
} as const;
